### ISSUE TITLE
win下雪碧图插件很难安装

### ISSUE THREAD

**Issue by kinglion** [duowan/generator-lego#3]
是不是可以考虑换下插件不用依赖与gm或者canvas的，这些个插件在win下就是无解的存在，每次折腾半点都安装不上。可以换成例如（gulp.spritesmith）

**Comment by twlk28** [comment]
win下是遇到啥问题呢？
如果报`找不到xx模块`的错误信息，cd到里面文件夹安装缺失的模块。可能网络问题引起的。

`gulp-spritesmith`依赖 `spritesmith` 模块，也需要安装图形引擎环境。 
详见：https://www.npmjs.com/package/spritesmith#engines

**Comment by kinglion** [comment]
> _gulp-spritesmith_依赖 _spritesmith_ 模块，也需要安装图形引擎环境。

就是这个图形引擎环境在win下比较难装，换了mac后，妥妥的了

**Comment by twlk28** [comment]
已更换引擎，默认不需安装第三方环境。恩，跨平台。
